data:
  shape:
  - 480
  - 640
  num_classes: 40
  unlabeled_id: 255

model:
  rgb_only:
    name: rgb_only
    use_hha: false
    rgb_only: true
    config:
      dropout: 0.0
  early_fusion_d:
    name: early_fusion_d
    use_hha: false
    rgb_only: false
    config:
      dropout: 0.0
  early_fusion_hha:
    name: early_fusion_hha
    use_hha: true
    rgb_only: false
    config:
      dropout: 0.0
  early_fusion_hha_att:
    name: early_fusion_hha_att
    use_hha: true
    rgb_only: false
    config:
      dropout: 0.2
  mid_fusion_hha_att:
    name: mid_fusion_hha_att
    use_hha: true
    rgb_only: false
    config:
      dropout: 0.2
      d_channels: 3
  late_fusion_d:
    name: late_fusion_d
    use_hha: false
    rgb_only: false
    config:
      dropout: 0.0
      d_channels: 1
  late_fusion_hha:
    name: late_fusion_hha
    use_hha: true
    rgb_only: false
    config:
      dropout: 0.0
      d_channels: 3
  late_fusion_hha_att:
    name: late_fusion_hha_att
    use_hha: true
    rgb_only: false
    config:
      dropout: 0.2
      d_channels: 3

output:
  directories:
    checkpoints: checkpoints
    logs: logs
    plots: plots
    results: results

train:
  seed: 42
  batch_size: 4
  epochs: 100
  num_workers: 4

  early_stopping:
    delta: 0.001
    mode: max
    patience: 10

  loss:
    cross_entropy:
      weight: None
    dice_loss:
      smooth: 1.0e-05
    focal_loss:
      gamma: 2
      reduction: mean
    weighted_cross_entropy:
      weight: None

  lr_scheduler:
    plateau:
      factor: 0.5
      mode: min
      patience: 3
      threshold: 0.001
    polynomial:
      power: 0.9
    step:
      gamma: 0.5
      step_size: 40
    cosine:
      eta_min: 0.000001

  optimizer:
    adam:
      weight_decay: 0.0001
    sgd:
      momentum: 0.9
      weight_decay: 0.0001
      nesterov: true
