data:
  shape:
  - 240
  - 360
  num_classes: 14
  paths:
    root_dir: data/NYUDepthv2_seg/data
    test_file: data/NYUDepthv2_seg/data/test.parquet
    train_file: data/NYUDepthv2_seg/data/split_train.parquet
    val_file: data/NYUDepthv2_seg/data/split_val.parquet
  unlabeled_id: 255

model:
  fcn_resnet50:
    name: fcn_resnet50
    rgb_only: true
    backbone: resnet50
    dropout: 0.3
  unet_resnet50:
    name: unet
    use_hha: false
    rgb_only: true
    config:
      encoder: resnet50
      dropout: 0.3
  unet_resnet101:
    name: unet
    use_hha: false
    rgb_only: true
    config:
      encoder: resnet101
      dropout: 0.3
  unet_depth_concatenate:
    name: unet_depth_concatenate
    use_hha: false
    rgb_only: false
    config:
      encoder: resnet50
      dropout: 0.3
  unet_hha_concatenate:
    name: unet_hha_concatenate
    use_hha: true
    rgb_only: false
    config:
      encoder: resnet50
      dropout: 0.3
  unet_depth_dual_encoder:
    name: unet_depth_dual_encoder
    use_hha: false
    rgb_only: false
    config:
      encoder: resnet50
      dropout: 0.3
  unet_hha_dual_encoder:
    name: unet_hha_dual_encoder
    use_hha: true
    rgb_only: false
    config:
      encoder: resnet50
      dropout: 0.3
  unet_hha_attention:
    name: unet_hha_attention
    use_hha: true
    rgb_only: false
    config:
      encoder: resnet50
      dropout: 0.3
      attention_reduction_ratio: 8

output:
  directories:
    checkpoints: checkpoints
    logs: logs
    plots: plots
    results: results

train:
  seed: 42
  batch_size: 8
  epochs: 100
  num_workers: 4

  early_stopping:
    delta: 0.001
    mode: min
    patience: 10

  loss:
    cross_entropy:
      weight: None
    dice_loss:
      smooth: 1.0e-05
    focal_loss:
      gamma: 0.5
      reduction: mean
    weighted_cross_entropy:
      weight: None

  lr_scheduler:
    plateau:
      factor: 0.5
      mode: min
      patience: 3
      threshold: 0.001
    polynomial:
      power: 0.9
    step:
      gamma: 0.3
      step_size: 30

  optimizer:
    adam:
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
      learning_rate: 0.005
      weight_decay: 0.001
    sgd:
      learning_rate: 0.002
      momentum: 0.9
      weight_decay: 0.0001
      nesterov: true
