data:
  shape:
  - 240
  - 360
  num_classes: 14
  paths:
    root_dir: data/NYUDepthv2_seg/data
    test_file: data/NYUDepthv2_seg/data/test.parquet
    train_file: data/NYUDepthv2_seg/data/split_train.parquet
    val_file: data/NYUDepthv2_seg/data/split_val.parquet
  unlabeled_id: 255

model:
  deeplabv3_resnet101:
    name: deeplabv3_resnet101
    rgb_only: true
    backbone: resnet101
    output_stride: 16
    dropout: 0.3
  deeplabv3_resnet50:
    name: deeplabv3_resnet50
    rgb_only: true
    backbone: resnet50
    output_stride: 16
    dropout: 0.3
  fcn_resnet101:
    name: fcn_resnet101
    rgb_only: true
    backbone: resnet101
    dropout: 0.3
  fcn_resnet50:
    name: fcn_resnet50
    rgb_only: true
    backbone: resnet50
    dropout: 0.3
  unet_resnet50:
    name: unet
    rgb_only: true
    config:
      encoder: resnet50
      dropout: 0.3
  unet_resnet101:
    name: unet
    rgb_only: true
    config:
      encoder: resnet101
      dropout: 0.3
  dual_encoder_unet:
    name: dual_encoder_unet
    rgb_only: false
    config:
      encoder: resnet50
      dropout: 0.3
  unet_depth_concatenate:
    name: unet_depth_concatenate
    rgb_only: false
    config:
      encoder: resnet50
      dropout: 0.3

output:
  directories:
    checkpoints: checkpoints
    logs: logs
    plots: plots
    results: results

train:
  seed: 42
  batch_size: 8
  epochs: 300
  num_workers: 4

  early_stopping:
    delta: 0.01
    mode: min
    patience: 15

  loss:
    cross_entropy:
      name: cross_entropy
      weight: None
    dice_loss:
      name: dice_loss
      smooth: 1.0e-05
    focal_loss:
      name: focal_loss
      alpha: 0.25
      gamma: 2.0
    weighted_cross_entropy:
      name: weighted_cross_entropy
      weight: None

  lr_scheduler:
    plateau:
      factor: 0.1
      mode: min
      patience: 5
      threshold: 0.0001
    polynomial:
      power: 0.9
    step:
      gamma: 0.1
      step_size: 10

  optimizer:
    adam:
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
      learning_rate: 0.005
      weight_decay: 0.001
    sgd:
      learning_rate: 0.007
      momentum: 0.9
      nesterov: false
      weight_decay: 0.001
