name: argus
channels:
  - conda-forge
  - defaults
dependencies:
  - libgoogle-cloud=2.36.0
  - libopentelemetry-cpp=1.18.0
  - yaml=0.2.5
  - brotli-python=1.1.0
  - libboost=1.86.0
  - aiohappyeyeballs=2.6.1
  - idna=3.10
  - libxcb=1.17.0
  - libgomp=15.1.0
  - cusparselt=0.7.0.0
  - libcrc32c=1.1.2
  - libopenvino-onnx-frontend=2025.0.0
  - aws-c-cal=0.8.7
  - libtheora=1.1.1
  - svt-av1=3.0.2
  - efficientnet-pytorch=0.7.1
  - libopenvino-auto-batch-plugin=2025.0.0
  - libtorch=2.6.0
  - optree=0.15.0
  - pyside6=6.8.3
  - cuda-nvvm-tools=12.9.41
  - charset-normalizer=3.4.2
  - readline=8.2
  - prometheus-cpp=1.3.0
  - setuptools=80.1.0
  - click=8.2.1
  - blinker=1.9.0
  - aws-c-event-stream=0.5.4
  - libmagma=2.8.0
  - tqdm=4.67.1
  - xorg-libxtst=1.2.5
  - markupsafe=3.0.2
  - lcms2=2.17
  - dav1d=1.2.1
  - libclang13=20.1.4
  - libsystemd0=257.4
  - aws-crt-cpp=0.31.0
  - libcurand=10.3.10.19
  - libgettextpo=0.24.1
  - parso=0.8.4
  - joblib=1.5.0
  - libnl=3.11.0
  - freeglut=3.2.2
  - libxslt=1.1.39
  - azure-storage-files-datalake-cpp=12.12.0
  - font-ttf-inconsolata=3.000
  - certifi=2025.4.26
  - libutf8proc=2.10.0
  - libde265=1.0.15
  - libheif=1.19.7
  - libcups=2.3.3
  - matplotlib=3.10.3
  - cuda-nvdisasm=12.9.19
  - urllib3=2.4.0
  - libopenvino-auto-plugin=2025.0.0
  - typing_extensions=4.13.2
  - libavif16=1.3.0
  - xorg-libxext=1.3.6
  - libglu=9.0.3
  - annotated-types=0.7.0
  - libev=4.33
  - timm=1.0.15
  - cycler=0.12.1
  - aiohttp=3.11.18
  - openh264=2.6.0
  - gmpy2=2.2.1
  - aws-c-io=0.17.0
  - aws-c-common=0.12.0
  - jedi=0.19.2
  - glew=2.1.0
  - xcb-util-image=0.4.0
  - libusb=1.0.28
  - python-dateutil=2.9.0.post0
  - cuda-crt-tools=12.9.41
  - multidict=6.4.3
  - proj=9.5.1
  - tzdata=2025b
  - executing=2.2.0
  - aws-checksums=0.2.3
  - libcufile=1.14.0.30
  - gflags=2.2.2
  - snappy=1.2.1
  - libopenvino-intel-npu-plugin=2025.0.0
  - libopenvino-paddle-frontend=2025.0.0
  - pycparser=2.22
  - propcache=0.3.1
  - libudev1=257.4
  - pexpect=4.9.0
  - libopenvino-intel-cpu-plugin=2025.0.0
  - libglvnd=1.7.0
  - jinja2=3.1.6
  - comm=0.2.2
  - python=3.13.3
  - msgpack-python=1.1.0
  - mpc=1.3.1
  - libbrotlidec=1.1.0
  - x264=1!164.3095
  - hdf5=1.14.3
  - decorator=5.2.1
  - libnvjpeg=12.4.0.16
  - cached-property=1.5.2
  - libparquet=19.0.1
  - gettext=0.24.1
  - typing-inspection=0.4.0
  - pysocks=1.7.1
  - libarrow-substrait=19.0.1
  - aws-c-compression=0.3.1
  - glfw=3.4
  - cuda-cuobjdump=12.9.26
  - libgcc-ng=15.1.0
  - libarrow-acero=19.0.1
  - lz4-c=1.10.0
  - keyutils=1.6.1
  - opencv=4.11.0
  - libarrow=19.0.1
  - blosc=1.21.6
  - eval_type_backport=0.2.2
  - pango=1.56.3
  - libegl=1.7.0
  - fontconfig=2.15.0
  - triton=3.2.0
  - contourpy=1.3.2
  - vtk-base=9.3.1
  - xorg-libsm=1.2.6
  - aws-c-http=0.9.4
  - dbus=1.13.6
  - aws-c-mqtt=0.12.2
  - cuda-cudart=12.9.37
  - ptyprocess=0.7.0
  - libbrotlicommon=1.1.0
  - librsvg=2.58.4
  - wslink=2.3.4
  - mysql-libs=9.0.1
  - pyparsing=3.2.3
  - libntlm=1.8
  - cuda-cupti=12.9.19
  - imageio=2.37.0
  - python_abi=3.13
  - libopenvino-pytorch-frontend=2025.0.0
  - pickleshare=0.7.5
  - nlohmann_json=3.12.0
  - libabseil=20240722.0
  - azure-core-cpp=1.14.0
  - ffmpeg=7.1.1
  - stringzilla=3.12.5
  - _libgcc_mutex=0.1
  - icu=75.1
  - x265=3.5
  - libopengl=1.7.0
  - libcblas=3.9.0
  - libopentelemetry-cpp-headers=1.18.0
  - munch=4.0.0
  - gl2ps=1.4.2
  - pandas=2.2.3
  - werkzeug=3.1.3
  - libllvm20=20.1.4
  - platformdirs=4.3.8
  - double-conversion=3.3.1
  - libblas=3.9.0
  - flask=3.1.1
  - xorg-libxau=1.0.12
  - xorg-libxinerama=1.1.5
  - libwebp-base=1.5.0
  - font-ttf-source-code-pro=2.038
  - libsndfile=1.2.2
  - libgcc=15.1.0
  - py-opencv=4.11.0
  - qhull=2020.2
  - re2=2024.07.02
  - libopenvino-hetero-plugin=2025.0.0
  - zstandard=0.23.0
  - brotli-bin=1.1.0
  - python-xxhash=3.5.0
  - ipykernel=6.29.5
  - krb5=1.21.3
  - tornado=6.4.2
  - dash=3.0.4
  - libuuid=2.38.1
  - pytz=2025.2
  - zlib=1.3.1
  - libgrpc=1.67.1
  - libpng=1.6.47
  - libpciaccess=0.18
  - cpython=3.13.3
  - libglx=1.7.0
  - zstd=1.5.7
  - libgfortran=15.1.0
  - libxml2=2.13.8
  - libarrow-dataset=19.0.1
  - ipython=9.2.0
  - cudnn=9.9.0.52
  - prompt-toolkit=3.0.51
  - tinyobjloader=1.0.7
  - pure_eval=0.2.3
  - libzip=1.11.2
  - exceptiongroup=1.2.2
  - attrs=25.3.0
  - jsoncpp=1.9.6
  - libre2-11=2024.07.02
  - aws-c-auth=0.8.6
  - libtiff=4.7.0
  - typing-extensions=4.13.2
  - embree=4.3.3
  - openjpeg=2.5.3
  - libcusolver=11.7.4.40
  - libzlib=1.3.1
  - libbrotlienc=1.1.0
  - aws-sdk-cpp=1.11.510
  - retrying=1.3.4
  - pyarrow-core=19.0.1
  - alsa-lib=1.2.14
  - xkeyboard-config=2.44
  - xorg-libxdamage=1.1.6
  - libnetcdf=4.9.2
  - xorg-libxfixes=6.0.1
  - libcurl=8.13.0
  - s2n=1.5.14
  - simsimd=6.4.3
  - utfcpp=4.0.6
  - libogg=1.3.5
  - ipython_pygments_lexers=1.1.1
  - pydantic=2.11.4
  - libxkbcommon=1.9.2
  - pillow=11.2.1
  - sympy=1.14.0
  - plotly=6.1.1
  - opencl-headers=2024.10.24
  - libgfortran5=15.1.0
  - pretrainedmodels=0.7.4
  - libuv=1.50.0
  - pybind11=2.13.6
  - h5py=3.13.0
  - lerc=4.0.0
  - scikit-learn=1.6.1
  - libhwloc=2.11.2
  - fonttools=4.57.0
  - libvpx=1.14.1
  - openssl=3.5.0
  - rav1e=0.7.1
  - hyperframe=6.1.0
  - cuda-version=12.9
  - munkres=1.1.4
  - stack_data=0.6.3
  - importlib-metadata=8.6.1
  - pytorch=2.6.0
  - libva=2.22.0
  - gmp=6.3.0
  - libclang-cpp20.1=20.1.4
  - libiconv=1.18
  - cuda-nvrtc=12.9.41
  - psutil=7.0.0
  - xorg-libxi=1.8.2
  - libcap=2.75
  - pugixml=1.15
  - segmentation-models-pytorch=0.5.0
  - gdk-pixbuf=2.42.12
  - traitlets=5.14.3
  - nomkl=1.0
  - pulseaudio-client=17.0
  - libthrift=0.21.0
  - libnghttp2=1.64.0
  - fonts-conda-ecosystem=1
  - expat=2.7.0
  - libasprintf-devel=0.24.1
  - libopenblas=0.3.29
  - xcb-util-keysyms=0.4.1
  - mpfr=4.2.1
  - tk=8.6.13
  - yarl=1.20.0
  - multiprocess=0.70.15
  - pcre2=10.44
  - pyzmq=26.4.0
  - tbb=2022.1.0
  - wayland=1.23.1
  - libopenvino-tensorflow-lite-frontend=2025.0.0
  - cairo=1.18.4
  - libpq=17.5
  - libcusparse=12.5.9.5
  - mpg123=1.32.9
  - c-ares=1.34.5
  - libaec=1.1.3
  - font-ttf-ubuntu=0.83
  - fmt=11.1.4
  - xorg-libxrandr=1.5.4
  - xcb-util-renderutil=0.3.10
  - cuda-nvcc-tools=12.9.41
  - xxhash=0.8.3
  - torchinfo=1.8.0
  - level-zero=1.22.0
  - gettext-tools=0.24.1
  - frozenlist=1.6.0
  - sdl3=3.2.12
  - xorg-libxscrnsaver=1.2.4
  - ocl-icd=2.3.3
  - cuda-nvtx=12.9.19
  - libdeflate=1.23
  - sqlite=3.49.2
  - libevent=2.1.12
  - libopenvino-intel-gpu-plugin=2025.0.0
  - libstdcxx-ng=15.1.0
  - asttokens=3.0.0
  - libopencv=4.11.0
  - azure-storage-blobs-cpp=12.13.0
  - networkx=3.4.2
  - pixman=0.46.0
  - nccl=2.26.5.1
  - cffi=1.17.1
  - itsdangerous=2.2.0
  - jupyter_client=8.6.3
  - cyrus-sasl=2.1.27
  - scipy=1.15.2
  - aom=3.9.1
  - fonts-conda-forge=1
  - giflib=5.2.2
  - nest-asyncio=1.6.0
  - libgl=1.7.0
  - libflac=1.4.3
  - six=1.17.0
  - xorg-libxt=1.3.1
  - libunwind=1.6.2
  - aws-c-s3=0.7.13
  - sleef=3.8
  - harfbuzz=10.4.0
  - matplotlib-base=3.10.3
  - libfreetype=2.13.3
  - font-ttf-dejavu-sans-mono=2.37
  - hdf4=4.2.15
  - glog=0.7.1
  - graphite2=1.3.13
  - narwhals=1.41.0
  - pydantic-core=2.33.2
  - libopus=1.5.2
  - libgoogle-cloud-storage=2.36.0
  - libexpat=2.7.0
  - liburing=2.9
  - libass=0.17.3
  - rdma-core=57.0
  - huggingface_hub=0.31.2
  - aiosignal=1.3.2
  - filelock=3.18.0
  - pypickle=1.1.5
  - liblzf=3.6
  - openexr=3.3.3
  - libcufft=11.4.0.6
  - _openmp_mutex=4.5
  - brotli=1.1.0
  - sdl2=2.32.54
  - ca-certificates=2025.4.26
  - open3d=0.19.0
  - eval-type-backport=0.2.2
  - libgcrypt-lib=1.11.0
  - openldap=2.6.9
  - libedit=3.1.20250104
  - safetensors=0.5.3
  - libsodium=1.0.20
  - dill=0.3.7
  - cuda-cudart_linux-64=12.9.37
  - cached_property=1.5.2
  - debugpy=1.8.14
  - loguru=0.7.3
  - libglib=2.84.1
  - liblapacke=3.9.0
  - wcwidth=0.2.13
  - pyarrow=19.0.1
  - mysql-common=9.0.1
  - jasper=4.2.5
  - aws-c-sdkutils=0.2.3
  - bzip2=1.0.8
  - zeromq=4.3.5
  - libopenvino-ir-frontend=2025.0.0
  - libssh2=1.11.1
  - azure-storage-common-cpp=12.8.0
  - xorg-libxcursor=1.2.3
  - python-tzdata=2025.2
  - liblzma=5.8.1
  - zipp=3.21.0
  - libcudss0=0.4.0.2
  - pyyaml=6.0.2
  - assimp=5.4.3
  - xorg-libxrender=0.9.12
  - libfreetype6=2.13.3
  - requests=2.32.3
  - numpy=2.2.5
  - ncurses=6.5
  - ld_impl_linux-64=2.43
  - qt6-main=6.8.3
  - torchvision-extra-decoders=0.0.2
  - xcb-util-cursor=0.1.5
  - threadpoolctl=3.6.0
  - imath=3.1.12
  - colorama=0.4.6
  - pygments=2.19.1
  - lame=3.100
  - freetype=2.13.3
  - attr=2.5.1
  - xorg-libice=1.1.2
  - jupyter_core=5.7.2
  - xcb-util-wm=0.4.2
  - xcb-util=0.4.1
  - libasprintf=0.24.1
  - liblapack=3.9.0
  - libstdcxx=15.1.0
  - libgpg-error=1.55
  - libnvjitlink=12.9.41
  - mpmath=1.3.0
  - hpack=4.1.0
  - pip=25.1.1
  - libmpdec=4.0.0
  - libjpeg-turbo=3.1.0
  - libvorbis=1.3.7
  - azure-identity-cpp=1.10.0
  - libopenvino=2025.0.0
  - pthread-stubs=0.4
  - xorg-libxcomposite=0.4.6
  - libopenvino-tensorflow-frontend=2025.0.0
  - packaging=25.0
  - fribidi=1.0.10
  - xorg-libx11=1.8.12
  - torchvision=0.21.0
  - libgettextpo-devel=0.24.1
  - matplotlib-inline=0.1.7
  - pybind11-global=2.13.6
  - orc=2.1.1
  - libprotobuf=5.28.3
  - xorg-libxxf86vm=1.1.6
  - libcublas=12.9.0.13
  - libsqlite=3.49.2
  - libdrm=2.4.124
  - h2=4.2.0
  - xorg-libxdmcp=1.1.5
  - kiwisolver=1.4.7
  - libffi=3.4.6
  - wayland-protocols=1.43
